name: branching-strategy
url: https://github.com/instana/branch-updater
description: Instana specific bot which supports our release/develop branches strategy
public: false
default_events:
  - push
  - status
default_permissions:
  contents: write
  metadata: read
  pull_requests: write
  statuses: read
